---
- hosts: all

  pre_tasks:
    - apt: update_cache=yes

  roles:
    - role: geerlingguy.java
      java_packages:
        - openjdk-7-jre
    - role: geerlingguy.jenkins
      jenkins_plugins:
        - ansicolor
        - build-pipeline-plugin
        - envinject
        - git
        - greenballs
    - role: geerlingguy.ruby
      ruby_install_gems:
        - bundler
      ruby_install_from_source: yes
      ruby_download_url: http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.1.tar.gz
      ruby_version: 2.2.1

  post_tasks:
    - name: Copy jenkins tasks to /var/lib/jenkins/jobs
      copy:
        src: jenkins-jobs/MyCoolApp
        dest: /var/lib/jenkins/jobs
        owner: jenkins
        group: jenkins
        mode: 0644
        directory_mode: 0755

    - name: Add user 'jenkins' to password-less sudoers
      lineinfile:
        dest: /etc/sudoers
        regexp: ^jenkins
        line: "jenkins ALL=(ALL) NOPASSWD: ALL"

  become: yes
